# Generated by Django 6.0.7 on 2026-07-10 10:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='phone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('force_password_change', models.BooleanField(default=False, verbose_name='force password change')),
                ('security_score', models.FloatField(default=0.0, verbose_name='security score')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('last_login_user_agent', models.TextField(blank=True, default='', verbose_name='last login user agent')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA enabled')),
                ('mfa_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='MFA secret')),
                ('trusted_devices', models.JSONField(blank=True, default=list, verbose_name='trusted devices')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='preferences')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='browser')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='operating system')),
                ('device', models.CharField(blank=True, default='', max_length=100, verbose_name='device')),
                ('is_mfa_verified', models.BooleanField(default=False, verbose_name='MFA verified')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='trusted device')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last activity')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'active session',
                'verbose_name_plural': 'active sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20, verbose_name='role')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='joined at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group membership',
                'verbose_name_plural': 'group memberships',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='custom_groups', through='users.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='browser')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='operating system')),
                ('device', models.CharField(blank=True, default='', max_length=100, verbose_name='device')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='failure reason')),
                ('session_key', models.CharField(blank=True, default='', max_length=255, verbose_name='session key')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='login at')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='logout at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login history',
                'verbose_name_plural': 'login histories',
                'ordering': ['-login_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['security_score'], name='users_user_securit_dc6e06_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['user', '-last_activity'], name='users_activ_user_id_5d6311_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['session_key'], name='users_activ_session_4a53e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-login_at'], name='users_login_user_id_6b0811_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='users_login_ip_addr_84051d_idx'),
        ),
    ]
