# Generated by Django 5.2.16 on 2026-07-29 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'sesión activa', 'verbose_name_plural': 'sesiones activas'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'grupo', 'verbose_name_plural': 'grupos'},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'verbose_name': 'membresía de grupo', 'verbose_name_plural': 'membresías de grupo'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-login_at'], 'verbose_name': 'historial de acceso', 'verbose_name_plural': 'historiales de acceso'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='group',
            name='min_password_length',
            field=models.PositiveSmallIntegerField(default=8, help_text='Longitud mínima que deben tener las contraseñas guardadas por miembros del grupo.', verbose_name='longitud mínima de contraseña'),
        ),
        migrations.AddField(
            model_name='group',
            name='trash_retention_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Días que una contraseña debe permanecer en la papelera antes de poder eliminarse permanentemente.', verbose_name='días en papelera'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='navegador'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='device',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='dispositivo'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='expira el'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='is_mfa_verified',
            field=models.BooleanField(default=False, verbose_name='MFA verificado'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='dispositivo confiable'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='última actividad'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='os',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sistema operativo'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='session_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='clave de sesión'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='iniciado el'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='agente de usuario'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='unido el'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Miembro'), ('admin', 'Admin')], default='member', max_length=20, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='navegador'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='dispositivo'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='motivo de fallo'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='login_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='acceso el'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cierre el'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='os',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sistema operativo'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='clave de sesión'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='success',
            field=models.BooleanField(default=True, verbose_name='éxito'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='agente de usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='forzar cambio de contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='nombre completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='es staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='es superusuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última actividad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='última IP de acceso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_user_agent',
            field=models.TextField(blank=True, default='', verbose_name='último user agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='MFA activado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='secreto MFA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='preferencias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_score',
            field=models.FloatField(default=0.0, verbose_name='puntaje de seguridad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trusted_devices',
            field=models.JSONField(blank=True, default=list, verbose_name='dispositivos confiables'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
