# Generated by Django 5.2.16 on 2026-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_activesession_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin_usuarios', 'Admin Usuarios'), ('estandar', 'Estándar')], default='estandar', max_length=20, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False, verbose_name='es staff'),
        ),
    ]
