# Generated by Django 5.0.14 on 2026-08-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_obsolete',
            field=models.BooleanField(default=False, help_text='Permite al usuario eliminar permanentemente registros del módulo de obsoletos.', verbose_name='borrar registros en obsoletos'),
        ),
    ]
