# Generated by Django 5.0.14 on 2026-08-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_can_delete_obsolete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_delete_obsolete',
        ),
    ]
