# Generated by Django 5.0.14 on 2026-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_can_delete_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo del contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nombre del contacto de emergencia'),
        ),
    ]
