# Generated by Django 5.0.14 on 2026-08-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_emergency_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='session_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Máximo de días que dura el token de sesión de los miembros de este grupo.', verbose_name='duración de sesión (días)'),
        ),
    ]
