# Generated by Django 5.0.14 on 2026-08-14 14:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_session_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeoCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='dirección IP')),
                ('country_code', models.CharField(blank=True, default='', max_length=2, verbose_name='código de país')),
                ('country_name', models.CharField(blank=True, default='', max_length=100, verbose_name='país')),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='resuelto el')),
            ],
            options={
                'verbose_name': 'caché geográfica IP',
                'verbose_name_plural': 'caché geográfica IPs',
                'ordering': ['-resolved_at'],
                'indexes': [models.Index(fields=['ip_address'], name='users_ipgeo_ip_addr_956f9b_idx')],
            },
        ),
    ]
