# Generated by Django 5.0.14 on 2026-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_export',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, los miembros del grupo no pueden exportar su bóveda ni sus secretos.', verbose_name='permitir exportación'),
        ),
    ]
