# Generated by Django 5.1.4 on 2026-08-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_group_allow_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_local_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Intentos fallidos de login local. Al alcanzar el límite la cuenta queda bloqueada para login local.', verbose_name='intentos fallidos de login local'),
        ),
    ]
