# Generated by Django 5.0.14 on 2026-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.TextField(blank=True, help_text='Clave de licencia proporcionada por el proveedor'),
        ),
    ]
