# Generated by Django 5.1.4 on 2026-08-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_license_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='expiry_alert_sent',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió la alerta de licencia próxima a vencer (para no duplicar).'),
        ),
    ]
