# Generated by Django 5.1.4 on 2026-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_license_expiry_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='sync_interval',
            field=models.PositiveIntegerField(default=3600, editable=False, help_text='Intervalo de sincronización automática con la API de licencias, en segundos (fijo, no editable).'),
        ),
    ]
