# Generated by Django 5.2.16 on 2026-08-04 22:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('category', models.CharField(choices=[('password', 'Contraseñas'), ('secret', 'Secretos'), ('user', 'Usuarios'), ('security', 'Seguridad'), ('domain', 'Dominios'), ('analysis', 'Análisis'), ('system', 'Sistema')], default='system', max_length=20, verbose_name='categoría')),
                ('icon', models.CharField(blank=True, default='bell', max_length=50, verbose_name='icono')),
                ('available_variables', models.JSONField(blank=True, default=list, verbose_name='variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'evento de notificación',
                'verbose_name_plural': 'eventos de notificación',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='TICOlvidé', max_length=255, verbose_name='nombre de la empresa')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='puerto')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='usuario')),
                ('password_encrypted', models.TextField(blank=True, default='', verbose_name='contraseña cifrada')),
                ('password_nonce', models.TextField(blank=True, default='')),
                ('password_salt', models.TextField(blank=True, default='')),
                ('encryption', models.CharField(choices=[('ssl', 'SSL (cifrado implícito)'), ('tls', 'STARTTLS (TLS)'), ('none', 'Sin cifrado')], default='tls', max_length=10, verbose_name='tipo de cifrado')),
                ('from_email', models.EmailField(blank=True, default='', max_length=255, verbose_name='correo remitente')),
                ('from_name', models.CharField(blank=True, default='TICOlvidé', max_length=255, verbose_name='nombre del remitente')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='tiempo de espera (s)')),
                ('is_active', models.BooleanField(default=False, verbose_name='activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'configuración SMTP',
                'verbose_name_plural': 'configuración SMTP',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='asunto')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='contenido HTML')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='contenido texto')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='mailer.notificationevent')),
            ],
            options={
                'verbose_name': 'plantilla de correo',
                'verbose_name_plural': 'plantillas de correo',
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='habilitado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo de notificaciones',
                'verbose_name_plural': 'grupos de notificaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupNotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='habilitado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_configs', to='mailer.notificationevent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to='mailer.notificationgroup')),
            ],
            options={
                'verbose_name': 'evento por grupo',
                'verbose_name_plural': 'eventos por grupo',
                'unique_together': {('group', 'event')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=255, verbose_name='destinatario')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='asunto')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido'), ('test', 'Prueba')], default='sent', max_length=10, verbose_name='estado')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enviado el')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='mailer.notificationevent')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='mailer.notificationgroup')),
            ],
            options={
                'verbose_name': 'registro de correo',
                'verbose_name_plural': 'registros de correo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mailer_emai_created_0b6568_idx'), models.Index(fields=['status'], name='mailer_emai_status_0e037f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='correo')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mailer.notificationgroup')),
            ],
            options={
                'verbose_name': 'destinatario',
                'verbose_name_plural': 'destinatarios',
                'ordering': ['email'],
                'unique_together': {('group', 'email')},
            },
        ),
    ]
