# Generated by Django 5.1.4 on 2026-08-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_password_expired_event'),
        ('users', '0011_user_failed_local_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationgroup',
            name='enterprise_groups',
            field=models.ManyToManyField(blank=True, help_text='Los miembros activos de estos grupos recibirán las notificaciones automáticamente.', related_name='notification_groups', to='users.group', verbose_name='grupos de la empresa'),
        ),
    ]
