# Generated by Django 5.1.4 on 2026-08-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_notificationgroup_enterprise_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Si es True, la notificación se envía directamente al usuario involucrado y no es configurable por grupos de notificaciones.', verbose_name='notificación personal del usuario'),
        ),
    ]
