# Generated by Django 5.1.4 on 2026-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_license_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='company_name',
            field=models.CharField(blank=True, default='TICO BOX', max_length=255, verbose_name='nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='from_name',
            field=models.CharField(blank=True, default='TICO BOX', max_length=255, verbose_name='nombre del remitente'),
        ),
    ]
