# Generated by Django 6.0.7 on 2026-07-10 10:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('azure', 'Microsoft Entra ID (Azure AD)')], default='azure', max_length=50, verbose_name='provider')),
                ('tenant_id', models.CharField(max_length=255, verbose_name='tenant ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='client ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='client secret')),
                ('redirect_uri', models.URLField(max_length=500, verbose_name='redirect URI')),
                ('logout_uri', models.URLField(blank=True, default='', max_length=500, verbose_name='logout URI')),
                ('scopes', models.CharField(default='openid profile email User.Read', max_length=500, verbose_name='scopes')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('sync_groups', models.BooleanField(default=False, verbose_name='sync groups')),
                ('just_in_time_provisioning', models.BooleanField(default=True, verbose_name='just-in-time provisioning')),
                ('allow_local_auth', models.BooleanField(default=True, verbose_name='allow local authentication')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'SSO configuration',
                'verbose_name_plural': 'SSO configurations',
            },
        ),
        migrations.CreateModel(
            name='SSOLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='user email')),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sso.ssoconfiguration')),
            ],
            options={
                'verbose_name': 'SSO log',
                'verbose_name_plural': 'SSO logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
