# Generated by Django 5.0.14 on 2026-08-04 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssoconfiguration',
            options={'verbose_name': 'configuración SSO', 'verbose_name_plural': 'configuraciones SSO'},
        ),
        migrations.AlterModelOptions(
            name='ssolog',
            options={'ordering': ['-created_at'], 'verbose_name': 'registro SSO', 'verbose_name_plural': 'registros SSO'},
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='allow_local_auth',
            field=models.BooleanField(default=True, verbose_name='permitir autenticación local'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='client_id',
            field=models.CharField(max_length=255, verbose_name='ID de cliente'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='client_secret',
            field=models.CharField(max_length=500, verbose_name='secreto de cliente'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='just_in_time_provisioning',
            field=models.BooleanField(default=True, verbose_name='aprovisionamiento justo a tiempo'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='logout_uri',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URI de cierre de sesión'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='provider',
            field=models.CharField(choices=[('azure', 'Microsoft Entra ID (Azure AD)')], default='azure', max_length=50, verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='redirect_uri',
            field=models.URLField(max_length=500, verbose_name='URI de redirección'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='scopes',
            field=models.CharField(default='openid profile email User.Read', max_length=500, verbose_name='alcances'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='sync_groups',
            field=models.BooleanField(default=False, verbose_name='sincronizar grupos'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='tenant_id',
            field=models.CharField(max_length=255, verbose_name='ID de tenant'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='ssolog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='acción'),
        ),
        migrations.AlterField(
            model_name='ssolog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='ssolog',
            name='details',
            field=models.TextField(blank=True, default='', verbose_name='detalles'),
        ),
        migrations.AlterField(
            model_name='ssolog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='ssolog',
            name='success',
            field=models.BooleanField(default=True, verbose_name='éxito'),
        ),
        migrations.AlterField(
            model_name='ssolog',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico del usuario'),
        ),
    ]
