# Generated by Django 5.2.16 on 2026-07-29 04:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('api_key', 'API Key'), ('ssh_key', 'Clave SSH'), ('credit_card', 'Tarjeta de Crédito'), ('custom', 'Personalizado')], max_length=20, verbose_name='tipo')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('data_encrypted', models.TextField(verbose_name='datos encriptados')),
                ('data_nonce', models.TextField(verbose_name='nonce datos')),
                ('data_salt', models.TextField(verbose_name='salt datos')),
                ('notes_encrypted', models.TextField(blank=True, default='', verbose_name='notas encriptadas')),
                ('notes_nonce', models.TextField(blank=True, default='', verbose_name='nonce notas')),
                ('notes_salt', models.TextField(blank=True, default='', verbose_name='salt notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'secreto',
                'verbose_name_plural': 'secretos',
                'ordering': ['-created_at'],
            },
        ),
    ]
