# Generated by Django 5.2.16 on 2026-07-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddField(
            model_name='secret',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='eliminado'),
        ),
    ]
