# Generated by Django 5.2.16 on 2026-07-29 04:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret_deleted_at_secret_is_deleted'),
        ('users', '0003_user_role_alter_user_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Puede Editar'), ('reshare', 'Puede Re-compartir')], default='read', max_length=20, verbose_name='permiso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira el')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='revocado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revocado el')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='secrets.secret')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_shares_initiated', to=settings.AUTH_USER_MODEL)),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_shares_received', to='users.group')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compartición de secreto',
                'verbose_name_plural': 'comparticiones de secretos',
                'indexes': [models.Index(fields=['secret', 'shared_with_user'], name='secrets_sec_secret__6f4b29_idx'), models.Index(fields=['shared_with_group'], name='secrets_sec_shared__dd4b7a_idx')],
            },
        ),
    ]
