# Generated by Django 5.0.14 on 2026-08-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_secret_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='is_obsolete',
            field=models.BooleanField(default=False, help_text='Secreto de origen desconocido que se conserva por seguridad en el módulo de obsoletos.', verbose_name='obsoleto'),
        ),
        migrations.AddField(
            model_name='secret',
            name='obsoleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='marcado obsoleto el'),
        ),
    ]
