# Generated by Django 5.1.4 on 2026-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0004_secret_is_obsolete_secret_obsoleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='secret',
            name='expiry_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='notificado el'),
        ),
    ]
