# Generated by Django 5.1.4 on 2026-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0005_secret_expires_at_secret_expiry_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretshare',
            name='permission',
            field=models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Puede Editar'), ('reshare', 'Puede Compartir')], default='read', max_length=20, verbose_name='permiso'),
        ),
    ]
