# Generated by Django 5.0.14 on 2026-10-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0006_alter_secretshare_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='expiry_warning_notified_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se envió la alerta de vencimiento próximo.', null=True, verbose_name='advertencia de vencimiento enviada el'),
        ),
    ]
