# Generated by Django 6.0.7 on 2026-07-10 10:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CREATED', 'Password Created'), ('PASSWORD_EDITED', 'Password Edited'), ('PASSWORD_DELETED', 'Password Deleted'), ('PASSWORD_VIEWED', 'Password Viewed'), ('PASSWORD_IMPORTED', 'Password Imported'), ('PASSWORD_EXPORTED', 'Password Exported'), ('PASSWORD_SHARED', 'Password Shared'), ('SHARE_REVOKED', 'Share Revoked'), ('USER_CREATED', 'User Created'), ('USER_EDITED', 'User Edited'), ('USER_DELETED', 'User Deleted'), ('USER_DISABLED', 'User Disabled'), ('USER_ENABLED', 'User Enabled'), ('GROUP_CREATED', 'Group Created'), ('GROUP_EDITED', 'Group Edited'), ('GROUP_DELETED', 'Group Deleted'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('SSO_CONFIGURED', 'SSO Configured'), ('SSO_ENABLED', 'SSO Enabled'), ('SSO_DISABLED', 'SSO Disabled'), ('POLICY_CHANGED', 'Policy Changed'), ('SETTINGS_CHANGED', 'Settings Changed'), ('FORCE_PASSWORD_CHANGE', 'Force Password Change'), ('SESSION_REVOKED', 'Session Revoked'), ('EXPORT_VAULT', 'Export Vault'), ('IMPORT_VAULT', 'Import Vault')], max_length=50, verbose_name='action')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='success', max_length=20, verbose_name='result')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='browser')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='operating system')),
                ('device', models.CharField(blank=True, default='', max_length=100, verbose_name='device')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
