# Generated by Django 5.0.14 on 2026-08-04 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'registro de auditoría', 'verbose_name_plural': 'registros de auditoría'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('PASSWORD_CREATED', 'Contraseña creada'), ('PASSWORD_EDITED', 'Contraseña editada'), ('PASSWORD_DELETED', 'Contraseña eliminada'), ('PASSWORD_VIEWED', 'Contraseña consultada'), ('PASSWORD_IMPORTED', 'Contraseña importada'), ('PASSWORD_EXPORTED', 'Contraseña exportada'), ('PASSWORD_SHARED', 'Contraseña compartida'), ('SHARE_REVOKED', 'Compartición revocada'), ('USER_CREATED', 'Usuario creado'), ('USER_EDITED', 'Usuario editado'), ('USER_DELETED', 'Usuario eliminado'), ('USER_DISABLED', 'Usuario deshabilitado'), ('USER_ENABLED', 'Usuario habilitado'), ('GROUP_CREATED', 'Grupo creado'), ('GROUP_EDITED', 'Grupo editado'), ('GROUP_DELETED', 'Grupo eliminado'), ('MFA_ENABLED', 'MFA habilitado'), ('MFA_DISABLED', 'MFA deshabilitado'), ('SSO_CONFIGURED', 'SSO configurado'), ('SSO_ENABLED', 'SSO habilitado'), ('SSO_DISABLED', 'SSO deshabilitado'), ('POLICY_CHANGED', 'Política cambiada'), ('SETTINGS_CHANGED', 'Configuración cambiada'), ('FORCE_PASSWORD_CHANGE', 'Forzar cambio de contraseña'), ('SESSION_REVOKED', 'Sesión revocada'), ('EXPORT_VAULT', 'Exportar bóveda'), ('IMPORT_VAULT', 'Importar bóveda')], max_length=50, verbose_name='acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='navegador'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, default='', verbose_name='detalles'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='device',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='dispositivo'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='os',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sistema operativo'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(choices=[('success', 'Éxito'), ('failure', 'Fallo'), ('pending', 'Pendiente')], default='success', max_length=20, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='agente de usuario'),
        ),
    ]
