# Generated by Django 5.0.14 on 2026-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Inicio de sesión fallido'), ('PASSWORD_CREATED', 'Contraseña creada'), ('PASSWORD_EDITED', 'Contraseña editada'), ('PASSWORD_DELETED', 'Contraseña eliminada'), ('PASSWORD_VIEWED', 'Contraseña consultada'), ('PASSWORD_IMPORTED', 'Contraseña importada'), ('PASSWORD_EXPORTED', 'Contraseña exportada'), ('PASSWORD_SHARED', 'Contraseña compartida'), ('SHARE_REVOKED', 'Compartición revocada'), ('USER_CREATED', 'Usuario creado'), ('USER_EDITED', 'Usuario editado'), ('USER_DELETED', 'Usuario eliminado'), ('USER_DISABLED', 'Usuario deshabilitado'), ('USER_ENABLED', 'Usuario habilitado'), ('GROUP_CREATED', 'Grupo creado'), ('GROUP_EDITED', 'Grupo editado'), ('GROUP_DELETED', 'Grupo eliminado'), ('MFA_ENABLED', 'MFA habilitado'), ('MFA_DISABLED', 'MFA deshabilitado'), ('SSO_CONFIGURED', 'SSO configurado'), ('SSO_ENABLED', 'SSO habilitado'), ('SSO_DISABLED', 'SSO deshabilitado'), ('POLICY_CHANGED', 'Política cambiada'), ('SETTINGS_CHANGED', 'Configuración cambiada'), ('FORCE_PASSWORD_CHANGE', 'Forzar cambio de contraseña'), ('SESSION_REVOKED', 'Sesión revocada'), ('EXPORT_VAULT', 'Exportar bóveda'), ('IMPORT_VAULT', 'Importar bóveda'), ('DATABASE_BACKUP', 'Backup de base de datos'), ('DATABASE_RESTORE', 'Restauración de base de datos')], max_length=50, verbose_name='acción'),
        ),
    ]
