# Generated by Django 6.0.7 on 2026-07-10 10:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/', verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('file_size', models.PositiveIntegerField(verbose_name='file size')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded at')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.CharField(blank=True, default='tag', max_length=50, verbose_name='icon')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='color')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.CharField(blank=True, default='folder', max_length=50, verbose_name='icon')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='color')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.URLField(blank=True, default='', max_length=2048, verbose_name='URL')),
                ('username_encrypted', models.TextField(blank=True, default='', verbose_name='encrypted username')),
                ('username_nonce', models.TextField(blank=True, default='')),
                ('username_salt', models.TextField(blank=True, default='')),
                ('password_encrypted', models.TextField(blank=True, default='', verbose_name='encrypted password')),
                ('password_nonce', models.TextField(blank=True, default='')),
                ('password_salt', models.TextField(blank=True, default='')),
                ('notes_encrypted', models.TextField(blank=True, default='', verbose_name='encrypted notes')),
                ('notes_nonce', models.TextField(blank=True, default='')),
                ('notes_salt', models.TextField(blank=True, default='')),
                ('sensitivity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='sensitivity')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorite')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='last accessed')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='access count')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'password entry',
                'verbose_name_plural': 'password entries',
                'ordering': ['-is_favorite', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_encrypted', models.TextField()),
                ('password_nonce', models.TextField()),
                ('password_salt', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'password history',
                'verbose_name_plural': 'password histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('read', 'Read Only'), ('write', 'Can Edit'), ('reshare', 'Can Reshare')], default='read', max_length=20, verbose_name='permission')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='revoked')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'share',
                'verbose_name_plural': 'shares',
            },
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='accessed at')),
            ],
            options={
                'verbose_name': 'share access log',
                'verbose_name_plural': 'share access logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(blank=True, default='#6c757d', max_length=7, verbose_name='color')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Vault', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'vault',
                'verbose_name_plural': 'vaults',
            },
        ),
    ]
