# Generated by Django 6.0.7 on 2026-07-10 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passwords', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='passwords.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='passwords.category'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='passwords.folder'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='passwords.passwordentry'),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='passwords.passwordentry'),
        ),
        migrations.AddField(
            model_name='share',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='passwords.passwordentry'),
        ),
        migrations.AddField(
            model_name='share',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='shared_with_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to='users.group'),
        ),
        migrations.AddField(
            model_name='share',
            name='shared_with_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareaccesslog',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='passwords.share'),
        ),
        migrations.AddField(
            model_name='shareaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='passwords.tag'),
        ),
        migrations.AddField(
            model_name='vault',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='passwords.vault'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'user', 'parent')},
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['entry', 'shared_with_user'], name='passwords_s_entry_i_028e98_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['shared_with_group'], name='passwords_s_shared__47b9f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['vault', 'is_deleted'], name='passwords_p_vault_i_e3600f_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['is_favorite'], name='passwords_p_is_favo_b65315_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['expires_at'], name='passwords_p_expires_861923_idx'),
        ),
    ]
