# Generated by Django 5.0.14 on 2026-07-15 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'archivo adjunto', 'verbose_name_plural': 'archivos adjuntos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name'], 'verbose_name': 'carpeta', 'verbose_name_plural': 'carpetas'},
        ),
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ['-is_favorite', 'name'], 'verbose_name': 'entrada de contraseña', 'verbose_name_plural': 'entradas de contraseña'},
        ),
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'historial de contraseña', 'verbose_name_plural': 'historiales de contraseña'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'verbose_name': 'compartición', 'verbose_name_plural': 'comparticiones'},
        ),
        migrations.AlterModelOptions(
            name='shareaccesslog',
            options={'ordering': ['-accessed_at'], 'verbose_name': 'registro de acceso a compartición', 'verbose_name_plural': 'registros de acceso a comparticiones'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'etiqueta', 'verbose_name_plural': 'etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='vault',
            options={'verbose_name': 'bóveda', 'verbose_name_plural': 'bóvedas'},
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='totp_secret_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='secreto TOTP cifrado'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='totp_secret_nonce',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='totp_secret_salt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='tamaño de archivo'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='nombre de archivo'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='tipo MIME'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='subido el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='tag', max_length=50, verbose_name='icono'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='icon',
            field=models.CharField(blank=True, default='folder', max_length=50, verbose_name='icono'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='access_count',
            field=models.PositiveIntegerField(default=0, verbose_name='conteo de accesos'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expira el'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='eliminado'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='favorito'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último acceso'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='notes_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='notas cifradas'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='password_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='contraseña cifrada'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='sensitivity',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='sensibilidad'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='username_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='usuario cifrado'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='versión'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='share',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expira el'),
        ),
        migrations.AlterField(
            model_name='share',
            name='is_revoked',
            field=models.BooleanField(default=False, verbose_name='revocado'),
        ),
        migrations.AlterField(
            model_name='share',
            name='permission',
            field=models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Puede Editar'), ('reshare', 'Puede Re-compartir')], default='read', max_length=20, verbose_name='permiso'),
        ),
        migrations.AlterField(
            model_name='share',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revocado el'),
        ),
        migrations.AlterField(
            model_name='shareaccesslog',
            name='accessed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='accedido el'),
        ),
        migrations.AlterField(
            model_name='shareaccesslog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='acción'),
        ),
        migrations.AlterField(
            model_name='shareaccesslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='name',
            field=models.CharField(default='Mi Bóveda', max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
