# Generated by Django 5.0.14 on 2026-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_alter_attachment_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='changes_summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='cambios'),
        ),
    ]
