# Generated by Django 5.2.16 on 2026-07-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_passwordhistory_changes_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='compromised_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última verificación'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='compromised_count',
            field=models.IntegerField(default=0, verbose_name='veces expuesta'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='is_compromised',
            field=models.BooleanField(default=False, verbose_name='comprometida'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['is_compromised'], name='passwords_p_is_comp_8e86dc_idx'),
        ),
    ]
