# Generated by Django 5.2.16 on 2026-08-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0005_passwordentry_compromised_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='expiry_notified_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se envió la notificación de vencimiento.', null=True, verbose_name='notificado de vencimiento el'),
        ),
    ]
