# Generated by Django 5.0.14 on 2026-08-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0006_passwordentry_expiry_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='is_obsolete',
            field=models.BooleanField(default=False, help_text='Contraseña de origen desconocido que se conserva por seguridad en el módulo de obsoletos.', verbose_name='obsoleta'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='obsoleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='marcada obsoleta el'),
        ),
    ]
