# Generated by Django 5.0.14 on 2026-08-13 16:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0007_passwordentry_is_obsolete_passwordentry_obsoleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_days', models.PositiveIntegerField(default=30, verbose_name='días solicitados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('denied', 'Denegada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido el')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='passwords.passwordentry')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_requests_answered', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests_addressed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de re-compartición',
                'verbose_name_plural': 'solicitudes de re-compartición',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry'], name='passwords_s_entry_i_60c8e8_idx'), models.Index(fields=['requested_by', 'status'], name='passwords_s_request_b1591b_idx')],
            },
        ),
    ]
