# Generated by Django 5.0.14 on 2026-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0008_sharerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerequest',
            name='requested_days',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Nulo significa compartición ilimitada.', null=True, verbose_name='días solicitados'),
        ),
    ]
