# Generated by Django 5.0.14 on 2026-08-15 13:01

from django.db import migrations, models


def backfill_strength(apps, schema_editor):
    from apps.passwords.encryption import (
        calculate_entropy,
        decrypt_field,
        password_hmac,
        password_strength,
    )
    PasswordEntry = apps.get_model('passwords', 'PasswordEntry')
    for entry in PasswordEntry.objects.exclude(password_encrypted='').only(
        'password_encrypted', 'password_nonce', 'password_salt'
    ):
        try:
            pwd = decrypt_field(
                entry.password_encrypted, entry.password_nonce, entry.password_salt
            )
        except Exception:
            continue
        if not pwd:
            continue
        strength = password_strength(pwd)
        entry.password_entropy = strength['entropy']
        entry.password_strength = strength['label']
        entry.password_hmac = password_hmac(pwd)
        entry.save(update_fields=['password_entropy', 'password_strength', 'password_hmac'])


def reverse_backfill(apps, schema_editor):
    PasswordEntry = apps.get_model('passwords', 'PasswordEntry')
    PasswordEntry.objects.update(
        password_entropy=0, password_strength='', password_hmac=''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0009_alter_sharerequest_requested_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='password_entropy',
            field=models.FloatField(default=0, verbose_name='entropía de la contraseña'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='password_hmac',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='HMAC de la contraseña'),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='password_strength',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='fortaleza de la contraseña'),
        ),
        migrations.RunPython(backfill_strength, reverse_backfill),
    ]
