# Generated by Django 5.1.4 on 2026-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0011_reencrypt_username_notes_fast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='url',
            field=models.URLField(blank=True, default='', max_length=10000, verbose_name='URL'),
        ),
    ]
