# Generated by Django 5.1.4 on 2026-09-10 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0012_alter_passwordentry_url'),
        ('secrets', '0005_secret_expires_at_secret_expiry_notified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token')),
                ('kind', models.CharField(choices=[('entry', 'Contraseña'), ('secret', 'Secreto')], max_length=10, verbose_name='tipo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('expires_at', models.DateTimeField(verbose_name='expira el')),
                ('days', models.PositiveSmallIntegerField(default=3, verbose_name='días de vigencia')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='revocado')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='visitas')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='último acceso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to='passwords.passwordentry')),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to='secrets.secret')),
            ],
            options={
                'verbose_name': 'enlace temporal',
                'verbose_name_plural': 'enlaces temporales',
                'ordering': ['-created_at'],
            },
        ),
    ]
