# Generated by Django 5.1.4 on 2026-09-12 13:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0013_securelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token')),
                ('password_encrypted', models.TextField(blank=True, default='', verbose_name='contraseña cifrada')),
                ('password_nonce', models.TextField(blank=True, default='')),
                ('password_salt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('expires_at', models.DateTimeField(verbose_name='expira el')),
                ('days', models.PositiveSmallIntegerField(default=3, verbose_name='días de vigencia')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='visitas')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='último acceso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contraseña compartida',
                'verbose_name_plural': 'contraseñas compartidas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SecureLink',
        ),
    ]
