# Generated by Django 5.1.4 on 2026-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0014_sharedpassword_delete_securelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpassword',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que se puede abrir el enlace. Vacío = ilimitado.', null=True, verbose_name='visitas máximas'),
        ),
        migrations.AlterField(
            model_name='sharedpassword',
            name='days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='días de vigencia'),
        ),
    ]
