# Generated by Django 5.1.4 on 2026-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0015_sharedpassword_max_uses_alter_sharedpassword_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpassword',
            name='max_uses',
            field=models.PositiveIntegerField(default=7, help_text='Número máximo de veces que se puede abrir el enlace. Límite fijo de 7; vacío = 7.', verbose_name='visitas máximas'),
        ),
    ]
