# Generated by Django 5.1.4 on 2026-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0016_alter_sharedpassword_max_uses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'solicitud de compartir', 'verbose_name_plural': 'solicitudes de compartir'},
        ),
        migrations.AlterField(
            model_name='share',
            name='permission',
            field=models.CharField(choices=[('read', 'Solo Lectura'), ('write', 'Puede Editar'), ('reshare', 'Puede Compartir')], default='read', max_length=20, verbose_name='permiso'),
        ),
    ]
