# Generated by Django 5.0.14 on 2026-10-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0017_alter_sharerequest_options_alter_share_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='expiry_warning_notified_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se envió el aviso de vencimiento próximo.', null=True, verbose_name='advertencia de vencimiento enviada el'),
        ),
    ]
