from django.urls import path
from . import views

app_name = 'passwords'

urlpatterns = [
    path('', views.vault_view, name='vault'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('entry/create/', views.entry_create, name='entry_create'),
    path('entry/<uuid:pk>/', views.entry_detail, name='detail'),
    path('entry/<uuid:pk>/edit/', views.entry_edit, name='entry_edit'),
    path('entry/<uuid:pk>/delete/', views.entry_delete, name='entry_delete'),
    path('entry/<uuid:pk>/restore/', views.entry_restore, name='entry_restore'),
    path('entry/<uuid:pk>/permanent-delete/', views.entry_permanent_delete, name='entry_permanent_delete'),
    path('entry/<uuid:pk>/favorite/', views.toggle_favorite, name='toggle_favorite'),
    path('entry/<uuid:pk>/share/', views.entry_share, name='entry_share'),
    path('entry/<uuid:pk>/move-folder/', views.entry_move_folder, name='entry_move_folder'),
    path('share/<uuid:share_id>/revoke/', views.revoke_share, name='revoke_share'),
    path('share/<uuid:share_id>/update-permission/', views.update_share_permission, name='update_share_permission'),
    path('share/requests/', views.share_requests_list, name='share_requests'),
    path('share/requests/<uuid:request_id>/approve/', views.share_request_approve, name='share_request_approve'),
    path('share/requests/<uuid:request_id>/deny/', views.share_request_deny, name='share_request_deny'),
    path('generate/', views.password_generator, name='password_generator'),
    path('import/', views.import_passwords, name='import'),
    path('export/', views.export_passwords, name='export'),
    path('trash/', views.trash_view, name='trash'),
    path('trash/empty/', views.empty_trash, name='empty_trash'),
    path('obsolete/', views.obsolete_view, name='obsolete'),
    path('entry/<uuid:pk>/mark-obsolete/', views.entry_mark_obsolete, name='entry_mark_obsolete'),
    path('folders/create/', views.folder_create, name='folder_create'),
    path('folders/<uuid:pk>/delete/', views.folder_delete, name='folder_delete'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<uuid:pk>/delete/', views.category_delete, name='category_delete'),
    path('tags/create/', views.tag_create, name='tag_create'),
    path('entry/<uuid:pk>/totp/generate/', views.totp_generate, name='totp_generate'),
    path('entry/<uuid:pk>/totp/remove/', views.totp_remove, name='totp_remove'),
    path('entry/<uuid:pk>/totp/qr/', views.totp_qr, name='totp_qr'),
    path('entry/<uuid:pk>/totp/current/', views.totp_current, name='totp_current'),
    path('entry/<uuid:pk>/copy-data/', views.entry_copy_data, name='entry_copy_data'),
    path('entry/<uuid:pk>/history/<uuid:hist_pk>/restore/', views.password_history_restore, name='password_history_restore'),
    path('onboarding/complete/', views.complete_onboarding, name='onboarding_complete'),
]
