# Generated by Django 5.0.14 on 2026-08-15 14:21

import apps.api_tokens.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Identificador del token, p.ej. "Informes PowerBI".', max_length=150, verbose_name='nombre')),
                ('key', models.CharField(default=apps.api_tokens.models.generate_token_key, editable=False, max_length=100, unique=True, verbose_name='clave')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creado el')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de caducidad. Déjalo vacío para que no expire.', null=True, verbose_name='caduca el')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'token de API',
                'verbose_name_plural': 'tokens de API',
                'ordering': ['-created_at'],
            },
        ),
    ]
